#!/bin/sh

untracked=`git status | grep "Untracked files:"`
if [ -n "$untracked" ]; then
    echo "Untracked file exists"
    exit 1
fi

if [ ! -e Makefile ]; then
    exit 0
fi

make test
if [ $? -ne 0 ]; then
    exit 1
fi

exit 0
